<?php 

function contact_form_block_info() {
    $blocks = array();
    $blocks['block_contact_form'] = array(
        'info' => t('Contact form'),
        'cache' => DRUPAL_NO_CACHE // this will exclude the block from Drupal cache
    );
    return $blocks;
  }


function contact_form_block_view($delta = '') {
   $block = [];
    switch ($delta) {

        case 'block_contact_form':
            $variables = array();
            
            $block['content'] = array(
                '#markup' => theme('block_contact_form', $variables),
                '#attached' => array(
                    'css' => array(
                      drupal_get_path('module', 'contact_form') . '/css/mdb.css',
                      drupal_get_path('module', 'contact_form') . '/css/custom.css',
                    ),
                    'js' => array(
                      drupal_get_path('module', 'contact_form') . '/js/custom.js',
                  ),
                ),
              );
            break;
          
        }
    return $block;
}


function contact_form_theme($existing, $type, $theme, $path) {

    $module_path = drupal_get_path('module', 'contact_form');
  

    $themes['block_contact_form'] = [
        'template'      => 'block--block--contact-form',
        'original hook' => 'block',
       
      ];

      return array(
        'block_contact_form' => array(
          'variables' => array(),
           'path'          => drupal_get_path('module', 'contact_form') . '/templates',
          'template' => 'block--block--contact-form',
        ),
      );
}



// function contact_form_theme($existing, $type, $theme, $path) {

//     // Custom template for that overrides the default block.tpl.php.
//     return [
//         'block_contact_form' => [
//             'variables' => [
//                 'elements' => NULL,
//                 'link' => NULL,
//             ]
//         ]
//     ];
//   }

// $block['content'] = array(
//     '#markup' => mymodule_testblock_content(),
//     '#attached' => array(
//         'css' => array(
//           drupal_get_path('module', 'mymodule') . '/css/mymodule.css',
//         ),
//         'js' => array(
//           drupal_get_path('module', 'mymodule') . '/js/mymodule.js',
//       ),
//     ),
//   );